kind: pipeline
type: docker
name: nuxtblog-admin

steps:
  - name: greeting
    image: node
    volumes:
      - name: dict
        path: /drone/src/dict
    commands:
      - npm i
      - npm run build

volumes:
  - name: dict
    host:
      path: /app/nginx/html/nuxtblog
