kind: pipeline
type: docker
name: nuxtblog-admin

steps:
  - name: greeting
    image: node
    # volumes:
    #   - name: dict
    #     path: ./dict
    commands:
      - echo hello world
      - ls
      - pwd
      - cd /
      - ls

# volumes:
#   - name: dict
#     host:
#       path: /app/nginx/html/nuxtblog
