kind: pipeline
type: docker
name: nuxtblog-admin

steps:
  - name: greeting
    image: node
    volumes:
      - name: dist
        path: /drone/src/dist
    commands:
      - npm --registry https://registry.npm.taobao.org i
      - npm run build

volumes:
  - name: dist
    host:
      path: /app/nginx/html/blog-admin
