kind: pipeline
type: docker
name: nuxtblog-admin

steps:
  - name: build
    image: node
    commands:
      - npm --registry https://registry.npmmirror.com install
      - npm run build

  - name: clean
    image: appleboy/drone-ssh
    settings:
      host: 121.40.126.12
      username: root
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 5m
      script:
        - rm -rf /app/nginx/html/blog-admin/*

  - name: upload
    image: appleboy/drone-scp
    settings:
      host: 121.40.126.12
      username: root
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 2m
      source:
        - ./dist
      target:
        - /app/nginx/html/blog-admin

  - name: mv
    image: appleboy/drone-ssh
    settings:
      host: 121.40.126.12
      username: root
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 5m
      script:
        - mv /app/nginx/html/blog-admin/dist/* /app/nginx/html/blog-admin/
        - rm -rf /app/nginx/html/blog-admin/dist
